language: python

python:

  - "3.6"

install:
    - pip install -r requirements.txt
    - pip install pytest 
    - pip install pytest-cov
    - pip install coveralls
    


script:
    - py.test --cov-report term-missing --cov=maths
    - py.test --doctest-modules --cov=maths3 --cov-report term-missing
  # - pytest
  # - pytest --cov=./
  #- py.test test_endpoints.py --cov=.

branches:
  only:
  - master

after-success:
- coveralls
- coverage report